### ISSUE TITLE
Use NPM instead of importmap?

### ISSUE THREAD

**Issue by papotte** [quouch/quouch#56]
I'm struggling to use importmap with custom Registries.

My suggestion would be to move to NPM, which might make it easier to navigate this. I'll make a PoC in a branch :)

From the Rails documentation:
https://guides.rubyonrails.org/v7.0/working_with_javascript_in_rails.html#adding-npm-packages-with-javascript-bundlers

From StackOverflow:
https://stackoverflow.com/questions/36602764/how-to-use-npm-packages-in-rails

**Comment by papotte** [comment]
@lisbethpurrucker do you have anything against this switch? :)

**Comment by lisbethpurrucker** [comment]
I actually kinda do. I migrated from a messy npm/yarn mix (my bad) to importmaps due to less dependencies, performance improvements etc. 

Can we not use npm selectively for edge cases like the icon package?

**Comment by papotte** [comment]
We could, but I'm afraid we'd end up with another mix. I'll try to find another way to install the package

**Comment by papotte** [comment]
Or maybe I'll just use submodules for now...
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by lisbethpurrucker** [comment]
If it is not possible any other way, we can for sure discuss if npm would make sense for other reasons longterm. But I would really love to avoid the switch back having realized how positively migrating affected the project.

**Comment by papotte** [comment]
Okay! I found a way through Submodules and it works quite well, except versioning is complicated/near impossible. Updating is a bit annoying so I would try to get the Icons as ready as possible before pushing to main.

I noticed that there are some Icons in the main page (the city, location pin, laughing emoji and checkbox) that are not included in the pack you sent me. I've tried parsing this as Icons but it's not possible for all of them (probably because of the way they were created). Are these custom made for Quouch?

I'd find it useful to gather all of the icons we need and decide how we can replace them. We are also using fontawesome and it would be nice to use some of theirs whenever possible, as it makes the work easier. Might make sense to make this in a pair programming session!

**Comment by lisbethpurrucker** [comment]
You are so right, there is more icons than the ones I sent you. Sorry for that, I just focused on the ones on Cloudinary at that point and did not mention the others. Babken made a few icons for us as for example on the landing page and some in the footer come from fontawesome as I wasn't able to find them on Nucleo, from where I have been downloading icons.

From my knowledge back then, I just reasoned my decision on fontawesome being bad for performance as it blocks rendering. Now, I believe that there is a way in which we can load the fontawesome icons asynchronously and hopefully only the ones we need instead of the whole library.

That being said - I am happy to rethink our approach and switch if it is the better option! Pair programming sounds good.

**Comment by papotte** [comment]
We might want to rethink how we're using FontAwesome as right now it is being downloaded from font-awesome on every render of the page. 
Since we have the gem installed, there might be a way to load them into the application without having a request to their servers.
